# Generated by Django 4.1.1 on 2022-09-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=40)),
                ('yosh', models.PositiveIntegerField()),
                ('kurs', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
