# Generated by Django 4.1.1 on 2022-09-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_talaba_yosh'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='jins',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
