# Generated by Django 4.1.1 on 2022-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_talaba_jins'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='shahar',
            field=models.CharField(blank=True, choices=[['Andijon', 'Andijon'], ["Farg'ona", "Farg'ona"], ["Marg'ilon", "Marg'ilon"], ['Toshkent', 'Toshkent']], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='talaba',
            name='universitet',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='jins',
            field=models.CharField(choices=[['Erkak', 'Erkak'], ['Ayol', 'Ayol']], default=None, max_length=20, null=True),
        ),
    ]
