# Generated by Django 4.1.1 on 2022-09-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_talaba_shahar_talaba_universitet_alter_talaba_jins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.PositiveIntegerField()),
                ('tirik', models.BooleanField()),
                ('millat', models.CharField(choices=[["O'zbek", "O'zbek"], ['Ingliz', 'Ingliz'], ['Turk', 'Turk'], ['Arab', 'Arab'], ['Rus', 'Rus']], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('yil', models.PositiveSmallIntegerField()),
                ('sahifa', models.PositiveSmallIntegerField()),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.author')),
            ],
        ),
    ]
