# Generated by Django 4.1.1 on 2022-09-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berilgan_sana', models.DateTimeField(auto_created=True)),
                ('qaytardi', models.CharField(choices=[['Ha', 'Ha'], ["Yo'q", "Yo'q"]], max_length=10)),
                ('qaytarilgan_sana', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book')),
            ],
        ),
    ]
