# Generated by Django 4.1.1 on 2022-09-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.book'),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.talaba'),
        ),
    ]
