# Generated by Django 4.1.1 on 2022-09-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_record_book_alter_record_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='qaytarilgan_sana',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
