# Generated by Django 4.1.1 on 2022-09-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_record_qaytarilgan_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='janr',
            field=models.CharField(blank=True, choices=[['Ilmiy', 'Ilmiy'], ['Badiiy', 'Badiiy'], ['Detektiv', 'Detektiv'], ['Psixologik', 'Psixologik'], ['Fantastik', 'Fantastik']], default=None, max_length=30, null=True),
        ),
    ]
